name: bigboxx-sync
base: core18
version: git
summary: Sync daemon of IoT middleware from e-Cattle platform for livestock farms
description: | 
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms. This module, named Synchronize, has the role to send 
  local data to cloud.

grade: devel
confinement: devmode

apps:
  synchronize:
    command: synchronize
    daemon: simple
    plugs: [home, network, network-bind]
    timer: 00:00-24:00/96
  
  gc:
    command: gc
    daemon: simple
    plugs: [home, network, network-bind]
    timer: 00:00-24:00/96

parts:
  synchronize:
    plugin: python
    python-version: python3
    source: .
    requirements: ['requirements.txt']
    
