name: bigboxx-sync
base: core18
version: git
summary: Synchronize for BigBoxx
description: |
      Synchronize for BigBoxx

grade: devel
confinement: devmode

apps:
  synchronize:
    command: synchronize
    daemon: simple
    plugs: [home, network, network-bind]
    timer: 00:00-24:00/96
  
  gc:
    command: gc
    daemon: simple
    plugs: [home, network, network-bind]
    timer: 00:00-24:00/96

parts:
  synchronize:
    plugin: python
    python-version: python3
    source: .
    requirements: ['requirements.txt']
    
